name: marie_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/game.jpg
   - assets/images/banniere-disney-lorcana.jpg
   - assets/images/lorcana.jpg
   - assets/images/magic.jpg
   - assets/images/hearthstone.jpg

